# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Ant build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TOMCAT_HOME: "tomcat"
    steps:
      - uses: actions/checkout@v3
      - name: Create Tomcat Directories
        run: mkdir -p tomcat/lib && mkdir -p tomcat/bin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/*.tar.gz
