name: Docker Run Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Create Build Reports Folder
      run: mkdir -p build/reports/tests
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: docker/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Run tests with docker compose
      run: docker compose -f docker/docker-compose.yml run epicsarchiver-test
      env:
        DOCKER_DEFAULT_PLATFORM: linux/amd64
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: build/reports/
